#!/bin/bash
# Config file installation script

set -euo pipefail

function run() { echo "$@"; "$@" 2>/dev/null; }
function append() { local out="$1"; shift; echo "echo $@ >> $out"; echo "$@" >> "$out"; }

if [ $# -lt 1 ] || [ $# -gt 2 ]; then
  echo "usage: $0 <bash|zsh> [full]"
  exit 1
fi

# shell selection
if [ "$1" = "bash" ] || [ "$1" = "zsh" ]; then
  if [ "$1" = "bash" ]; then
    echo "==== bash setup"
    run ln -s $HOME/.config/shell/shellrc  $HOME/.bashrc
    run ln -s $HOME/.config/shell/inputrc  $HOME/.inputrc
    run ln -s $HOME/.config/shell/profile  $HOME/.bash_profile
  elif [ "$1" = "zsh" ]; then
    echo "==== zsh setup"
    run ln -s $HOME/.config/shell/shellrc  $HOME/.zshrc    || true
    run ln -s $HOME/.config/shell/profile  $HOME/.zprofile || true
    run ln -s $HOME/.config/shell/zshenv   $HOME/.zshenv   || true
  fi
  echo "==== shared shell setup"
  run run mkdir -p $HOME/.local/bin
  run ln -s $HOME/.config/meta/ding      $HOME/.local/bin/ding  || true
  run ln -s $HOME/.config/meta/run-tmate $HOME/.local/bin/tmate || true
  run ln -s $HOME/.config/meta/tinty     $HOME/.local/bin/tinty || true
  echo "==== writing ssh-agent configuration"
  run mkdir -pm 700 "$HOME/.ssh"
  append "$HOME/.ssh/config" "AddKeysToAgent yes"
  run chmod 600 "$HOME/.ssh/config"
  echo "==== enabling ssh-agent service"
  run systemctl --user enable ssh-agent.service
  run systemctl --user start ssh-agent.service
else
  echo "usage: link.sh (bash|zsh) [full]"
  exit 1
fi

# in WSLv2 mode, let linux exec windows binaries
if grep -qi "microsoft-standard-WSL2" /proc/version 2>/dev/null; then
  sudo sh -c 'echo :WSLInterop:M::MZ::/init:PF > /usr/lib/binfmt.d/WSLInterop.conf'
  run ln -s $HOME/.config/meta/win32yank.exe $HOME/.local/bin/win32yank.exe || true
# in full mode, install graphics/sound configs
elif [ $# -eq 2 ] && [ "$2" = "full" ]; then
  echo "==== full setup"
  run ln -s $HOME/.config/native/default-asoundrc $HOME/.asoundrc || true
  run ln -s $HOME/.config/native/xinitrc          $HOME/.xinitrc  || true
  echo "For High-DPI screens, please make sure browsers are scaled properly"
  echo "For chromium: check config/display/chromium-flags.conf"
  echo "For firefox: do online search"
# otherwise, ignore this step
else
  echo "Console installations will not link graphics/sound config files"
  echo "For full installation, re-run with as:"
  echo "$ link.sh $1 full"
fi
