#!/bin/bash

DING_PORT=${DING_PORT:-8888}
WINDOWS_SOUND_PATH=C:\\WINDOWS\\Media\\notify.wav
OTHER_SOUND_PATH=$HOME/.config/data/ding.mp3

# run a command if we have one
[ $# -ne 0 ] && $@

# if we are running remotely, send the ding to the local computer ding-server via SSH tunnel on $PORT
if [ -n "$SSH_CLIENT" ]; then
  exec netcat localhost "$DING_PORT" &>/dev/null <<< $'\n' &

# if we are running locally, play the ding
else

  # if uname -a contains microsoft, we are in WSL, play ding via powershell
  if (uname -a | grep -qi microsoft); then
   powershell.exe -c "(New-Object Media.SoundPlayer '$WINDOWS_SOUND_PATH').PlaySync();" &>/dev/null &

  # otherwise, we are on linux/mac, play ding via ffplay
  else
    # -nodisp         - do not show visualization
    # -autoexit       - exit after playing
    # -loglevel quiet - do not print anything on the command line
    ffplay -nodisp -autoexit -loglevel quiet "$OTHER_SOUND_PATH" &>/dev/null &
  fi
fi
