#!/bin/bash

PORT=8888
WINDOWS_SOUND_PATH=C:\\WINDOWS\\Media\\notify.wav
OTHER_SOUND_PATH=$HOME/.config/data/ding.mp3

# if we are running remotely, send the ding to the local computer ding-server via SSH tunnel
if [ -n "$SSH_CLIENT" ]; then
  exec netcat localhost "$PORT" &>/dev/null <<< "" &
# if we are running locally, play the ding
else
  # if the subshell retunns true, we are in WSL
  if (cat /proc/version | grep -qi microsoft)
  then
    exec powershell.exe -c "(New-Object Media.SoundPlayer '$WINDOWS_SOUND_PATH').PlaySync();" &>/dev/null &
  else
    # -nodisp         - do not show visualization
    # -autoexit       - exit after playing
    # -loglevel quiet - do not print anything on the command line
    exec ffplay -nodisp -autoexit -loglevel quiet "$OTHER_SOUND_PATH" &>/dev/null &
  fi
fi
