#!/bin/bash

LOCAL="fec0:0:0:ffff::"

function write_resolv() {
  CLIENT_LIST=$(powershell.exe -Command "Get-DnsClientServerAddress  | Select-Object -ExpandProperty ServerAddresses")
  echo "# This file was automatically generated by WSL. To stop automatic generation of this file, remove this line."
  for client in $CLIENT_LIST
  do
    if [[ "$client" != ${LOCAL}* ]]; then
      echo "nameserver $client"
    fi
  done
}

RESOLV_FILE=$(write_resolv)
echo "writing to /etc/resolv.conf..."
echo -n "$RESOLV_FILE"
echo -n "$RESOLV_FILE" > /etc/resolv.conf
