#!/bin/bash

CLIENT_LIST=$(powershell.exe -Command "Get-DnsClientServerAddress  | Select-Object -ExpandProperty ServerAddresses")
LOCAL="fec0:0:0:ffff::"
echo "# This file was automatically generated by WSL. To stop automatic generation of this file, remove this line."
for client in $CLIENT_LIST
do
  if [[ "$client" != ${LOCAL}* ]]; then
    echo "nameserver $client"
  fi
done
